# Generated by Django 4.0.1 on 2023-11-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.CharField(choices=[('Big Groups', 'BIG_GROUPS'), ('One on Ones', '1On1')], default='1On1', max_length=20),
            preserve_default=False,
        ),
    ]
