# Generated by Django 4.0.1 on 2023-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.CharField(choices=[('BIG_GROUPS', 'Big Groups'), ('1On1', 'One on Ones')], max_length=20),
        ),
    ]
