# Generated by Django 4.0.1 on 2023-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.CharField(choices=[('BIG_GROUPS', 'Big Groups'), ('1On1', 'One on Ones')], default='1On1', max_length=20),
            preserve_default=False,
        ),
    ]
