# Generated by Django 4.0.1 on 2023-11-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
