# Generated by Django 4.0.1 on 2023-11-20 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_dislikes_remove_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time',
            field=models.TimeField(),
        ),
    ]
