# Generated by Django 4.0.1 on 2023-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_workshop_date_alter_workshop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='date',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
