# Generated by Django 5.0 on 2023-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_organisation_profile_racnumber_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
