# Generated by Django 4.0.2 on 2023-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_racnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACNumber',
            field=models.IntegerField(),
        ),
    ]
