# Generated by Django 4.0.2 on 2023-12-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='consent_to_share',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referredTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.organisation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='walk_in',
            field=models.BooleanField(),
        ),
    ]
