# Generated by Django 4.0.2 on 2023-12-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_profile_consent_to_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='initialDecision',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_open',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_accessed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_needed',
            field=models.CharField(max_length=500),
        ),
    ]
