# Generated by Django 4.0.2 on 2023-12-08 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_profile_initialdecision_alter_profile_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RACdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
