# Generated by Django 4.0.2 on 2023-12-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_profile_issue_profile_raised_by_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACdate',
            field=models.DateField(blank=True),
        ),
    ]
