# Generated by Django 4.0.2 on 2023-12-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_profile_racdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='issue',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
