# Generated by Django 4.0.2 on 2023-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_profile_referredto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_accessed',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_needed',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
