# Generated by Django 4.0.2 on 2023-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_profile_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='support_needed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
