# Generated by Django 4.0.2 on 2023-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_profile_support_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='initialDecision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referredTo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_accessed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
