# Generated by Django 4.0.2 on 2023-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_profile_initialdecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
