# Generated by Django 4.0.2 on 2023-12-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_profile_racdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
