# Generated by Django 4.1.6 on 2023-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_remove_profile_age_remove_profile_issue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="signature_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
