# Generated by Django 4.1.6 on 2023-12-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_profile_signature_profile_signature_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cr_team",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
