# Generated by Django 4.0.1 on 2024-01-23 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_profile_referredto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
