# Generated by Django 4.0.1 on 2024-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_followup_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referredTo',
            field=models.CharField(blank=True, choices=[('Devon MIND', 'Devon MIND')], max_length=100, null=True),
        ),
    ]
