# Generated by Django 4.0.1 on 2024-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_profile_referredto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referredToMore',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referredTo',
            field=models.CharField(blank=True, choices=[('Devon MIND', 'Devon MIND'), ('HMHT', 'HMHT'), ('GP', 'GP'), ('Resilient Women', 'Resilient Women'), ('Wellbeing Exeter', 'Wellbeing Exeter'), ('Crisis Team', 'Crisis Team'), ('OHMT', 'OHMT'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
