# Generated by Django 4.2.11 on 2024-03-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_profile_referredtomore_alter_profile_referredto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='time',
            new_name='date',
        ),
    ]
