# Generated by Django 4.2.11 on 2024-03-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_time_workshop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
