# Generated by Django 4.2.11 on 2024-03-07 23:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_profile_dislikes_alter_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Large Groups', 'Large Groups'), ("1o1's", "1o1's"), ('The Gays', 'The Gays')], max_length=200),
        ),
    ]
