# Generated by Django 4.2.11 on 2024-03-08 00:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='concern_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Large Groups', 'Large Groups'), ("1o1's", "1o1's")], max_length=200),
        ),
    ]
