# Generated by Django 4.2.11 on 2024-03-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_profile_concern_level_alter_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='concern_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
    ]
