# Generated by Django 4.2.11 on 2024-03-10 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_profile_concern_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='3 Johnson Drive', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='concern_description',
            field=models.CharField(default='Alcohol abuse', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_contact',
            field=models.CharField(default='07723482834', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_name',
            field=models.CharField(default='James', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_org',
            field=models.CharField(default='University', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_risk',
            field=models.CharField(default='Alcohol Abuse', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_team',
            field=models.CharField(default='University', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='mh@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gp_surgery',
            field=models.CharField(default='Mount Pleasant', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nhs_number',
            field=models.IntegerField(default=4553353),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_contact',
            field=models.CharField(default='07463635354', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_name',
            field=models.CharField(default='James Heart', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.CharField(default='JCH', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
