# Generated by Django 4.2.11 on 2024-03-10 15:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_profile_dislikes_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dislikes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Large Groups', 'Large Groups'), ("1o1's", "1o1's")], max_length=200),
        ),
    ]
