# Generated by Django 4.2.11 on 2024-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_happiness_after_alter_happiness_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_plan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
