# Generated by Django 4.1.6 on 2024-03-17 13:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_profile_personal_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
