# Generated by Django 4.1.6 on 2024-03-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_profile_encrypted_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='encrypted_name',
        ),
    ]
