# Generated by Django 4.1.6 on 2024-03-17 18:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_encryptedprofile_nhs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cr_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
