# Generated by Django 4.1.6 on 2024-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_profile_person_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person_contact',
            field=models.CharField(max_length=100),
        ),
    ]
