# Generated by Django 4.1.6 on 2024-03-18 12:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_profile_person_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person_contact',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
