# Generated by Django 4.1.6 on 2024-03-18 12:24

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='initialDecision',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_plan',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_accessed',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='support_needed',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
    ]
