# Generated by Django 4.1.6 on 2024-03-18 13:04

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_profile_initialdecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cr_contact',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_org',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_risk',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_team',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
