# Generated by Django 4.1.6 on 2024-03-18 15:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_profile_cr_contact_alter_profile_cr_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RACdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='concern_description',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_contact',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_org',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cr_risk',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gp_surgery',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nhs_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_contact',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='walk_in',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
