# Generated by Django 4.1.6 on 2024-03-19 13:21

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_profile_signature_alter_profile_signature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nhs_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
    ]
