# Generated by Django 4.2.11 on 2024-03-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='happiness',
            name='attended',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
