# Generated by Django 4.1.6 on 2024-03-25 14:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_happiness_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_alcoholic',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False, null=True)),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_homeless',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False, null=True)),
        ),
        migrations.AddField(
            model_name='profile',
            name='taking_medication',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False, null=True)),
        ),
        migrations.AddField(
            model_name='profile',
            name='using_drugs',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False, null=True)),
        ),
    ]
